[package]

name = "external"
version = "0.0.1"
authors = ["external <jan.falkin@eluv.io>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/JanFalkin/external"
description = "A Rust wasm library"
workspace = "../.."

[lib]
name = "external"
crate-type = ["rlib", "cdylib"]

[dependencies]
elvwasm = {path = "../.."}
wapc = "1.0.0"
wapc-guest = "1.0"
serde = "1.0.156"
serde_json = "1.0.94"
serde_derive = "1.0.156"
base64 = "0.21.0"
scopeguard = "1.1.0"