[package]

name = "external"
version = "0.0.1"
authors = ["external <jan.falkin@eluv.io>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/JanFalkin/external"
description = "A Rust wasm library"
workspace = "../.."

[lib]
name = "external"
crate-type = ["rlib", "cdylib"]

[dependencies]
elvwasm = {path = "../.."}
wapc = "*"
wapc-guest = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
base64 = "0.21.0"
scopeguard = "1.1.0"